baseURL = "https://salinasalejandro.github.io/my_launchx_blog/"
languageCode = "es-mx"
title = "BitÃ¡cora de Viaje de Alejandro 'Dykeo' Salinas"
theme = "hugo-winston-theme"
relativeURLs = true
canonifyURLs = true

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 3

[params]
  google_analytics_id = ""
  # Hey Explorer aquÃ­ pon tu twitter ðŸ‘‡
  twitter_handle = "No tengo UnU"
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = false
  addFrame = true
  addDot = true
